/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "oasntupyzbjqlyhitufk";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hc250dXB5emJqcWx5aGl0dWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MTIxOTcsImV4cCI6MjA3ODQ4ODE5N30.9e8CBNuCJr3OudHYIQcrJPscC-VaVVFQkqipi7gEZWs";
